[project]
name = "postgresql-mcp-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "mcp[cli]>=1.26.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
]
