apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents-db-mcp
  namespace: agents-db-mcp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agents-db-mcp
  template:
    metadata:
      labels:
        app: agents-db-mcp
    spec:
      containers:
        - name: agents-db-mcp
          image: ghcr.io/commonrservices/postgresql-mcp-python:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: postgres-agents-svc.pg-agents.svc.cluster.local 
            - name: DB_PORT
              value: "5433"
            - name: DB_NAME
              value: netaiprocesses
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: agents-db-mcp-secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: agents-db-mcp-secrets
                  key: db-password